apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: openshift-kube-descheduler-operator
  namespace: openshift-kube-descheduler-operator
spec:
  upgradeStrategy: Default
  targetNamespaces:
    - openshift-kube-descheduler-operator
