apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-kube-descheduler-operator
  namespace: openshift-kube-descheduler-operator
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  channel: stable
  installPlanApproval: Automatic
  name: cluster-kube-descheduler-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
