apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-dev-external-secrets
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/instance: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: openshift-operators
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: apps/external-secrets
    repoURL: 'https://github.com/vrutkovs/kcd-cz-demo'
    targetRevision: HEAD
  syncPolicy:
    automated: {}
