apiVersion: hypershift.openshift.io/v1beta1
kind: HostedCluster
metadata:
  name: vrutkovs-dev
  namespace: clusters
  finalizers:
    - hypershift.openshift.io/finalizer
  labels:
    hypershift.openshift.io/auto-created-for-infra: vrutkovs-dev
spec:
  fips: false
  release:
    image: 'quay.io/openshift-release-dev/ocp-release:4.12.16-x86_64'
  dns:
    baseDomain: devcluster.openshift.com
    privateZoneID: Z048391011Z9LJR2TEW8U
    publicZoneID: Z3URY6TWQ91KVV
  controllerAvailabilityPolicy: SingleReplica
  infraID: vrutkovs-dev
  etcd:
    managed:
      storage:
        persistentVolume:
          size: 4Gi
          storageClassName: gp3-csi
        type: PersistentVolume
    managementType: Managed
  infrastructureAvailabilityPolicy: SingleReplica
  platform:
    aws:
      cloudProviderConfig:
        subnet:
          id: subnet-026420de2b0107a49
        vpc: vpc-050667014849d2e4e
        zone: us-east-2a
      endpointAccess: Public
      region: us-east-2
      resourceTags:
        - key: kubernetes.io/cluster/vrutkovs-dev
          value: owned
      rolesRef:
        controlPlaneOperatorARN: 'arn:aws:iam::269733383066:role/vrutkovs-dev-control-plane-operator'
        imageRegistryARN: 'arn:aws:iam::269733383066:role/vrutkovs-dev-openshift-image-registry'
        ingressARN: 'arn:aws:iam::269733383066:role/vrutkovs-dev-openshift-ingress'
        kubeCloudControllerARN: 'arn:aws:iam::269733383066:role/vrutkovs-dev-cloud-controller'
        networkARN: >-
          arn:aws:iam::269733383066:role/vrutkovs-dev-cloud-network-config-controller
        nodePoolManagementARN: 'arn:aws:iam::269733383066:role/vrutkovs-dev-node-pool'
        storageARN: >-
          arn:aws:iam::269733383066:role/vrutkovs-dev-aws-ebs-csi-driver-controller
    type: AWS
  secretEncryption:
    aescbc:
      activeKey:
        name: vrutkovs-dev-etcd-encryption-key
    type: aescbc
  networking:
    clusterNetwork:
      - cidr: 10.132.0.0/14
    machineNetwork:
      - cidr: 10.0.0.0/16
    networkType: OVNKubernetes
    serviceNetwork:
      - cidr: 172.31.0.0/16
  clusterID: 0a760474-0d69-447d-89d0-e89bcccaa5d2
  pullSecret:
    name: vrutkovs-dev-pull-secret
  issuerURL: 'https://vrutkovs-hypershift-demo.s3.us-east-2.amazonaws.com/vrutkovs-dev'
  sshKey:
    name: vrutkovs-dev-ssh-key
  autoscaling: {}
  olmCatalogPlacement: management
  services:
    - service: APIServer
      servicePublishingStrategy:
        type: LoadBalancer
    - service: OAuthServer
      servicePublishingStrategy:
        type: Route
    - service: Konnectivity
      servicePublishingStrategy:
        type: Route
    - service: Ignition
      servicePublishingStrategy:
        type: Route
    - service: OVNSbDb
      servicePublishingStrategy:
        type: Route
