apiVersion: hypershift.openshift.io/v1beta1
kind: HostedCluster
metadata:
  name: vrutkovs-dev
  namespace: clusters
  finalizers:
    - hypershift.io/aws-oidc-discovery
    - hypershift.openshift.io/finalizer
  annotations:
    cluster.open-cluster-management.io/hypershiftdeployment: local-cluster/vrutkovs-dev
    cluster.open-cluster-management.io/managedcluster-name: vrutkovs-dev
  labels:
    hypershift.openshift.io/auto-created-for-infra: vrutkovs-dev
spec:
  fips: false
  release:
    image: 'quay.io/openshift-release-dev/ocp-release:4.12.16-x86_64'
  dns:
    baseDomain: devcluster.openshift.com
  controllerAvailabilityPolicy: SingleReplica
  infraID: vrutkovs-dev
  etcd:
    managed:
      storage:
        persistentVolume:
          size: 4Gi
          storageClassName: gp3-csi
        type: PersistentVolume
    managementType: Managed
  infrastructureAvailabilityPolicy: SingleReplica
  platform:
    aws:
      cloudProviderConfig:
        zone: us-east-2a
      endpointAccess: Public
      region: us-east-2
      resourceTags:
        - key: kubernetes.io/cluster/vrutkovs-dev
          value: owned
    type: AWS
  secretEncryption:
    aescbc:
      activeKey:
        name: vrutkovs-dev-etcd-encryption-key
    type: aescbc
  networking:
    clusterNetwork:
      - cidr: 10.132.0.0/14
    machineNetwork:
      - cidr: 10.0.0.0/16
    networkType: OVNKubernetes
    serviceNetwork:
      - cidr: 172.31.0.0/16
  pullSecret:
    name: vrutkovs-dev-pull-secret
  issuerURL: 'https://vrutkovs-hypershift-demo.s3.us-east-1.amazonaws.com/vrutkovs-dev'
  sshKey:
    name: vrutkovs-dev-ssh-key
  autoscaling: {}
  olmCatalogPlacement: management
  services:
    - service: APIServer
      servicePublishingStrategy:
        type: LoadBalancer
    - service: OAuthServer
      servicePublishingStrategy:
        type: Route
    - service: Konnectivity
      servicePublishingStrategy:
        type: Route
    - service: Ignition
      servicePublishingStrategy:
        type: Route
    - service: OVNSbDb
      servicePublishingStrategy:
        type: Route
