apiVersion: config.openshift.io/v1
kind: OperatorHub
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  disableAllDefaultSources: true
  sources:
  - name: "community-operators"
    disabled: false
  - name: "redhat-operators"
    disabled: false
