apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deploy-to-stage
spec:
  description: |
    This pipeline clones a git repo, builds a Docker image with Buildah,
    pushes it to a registry and deploys this image from manifests
  workspaces:
  - name: app-source
  - name: dockerconfig-ws
  tasks:
  - name: fetch-source
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: app-source
    params:
    - name: url
      value: https://github.com/vrutkovs/color-demo
    - name: revision
      value: main
  - name: build-image
    taskRef:
      kind: ClusterTask
      name: buildah
    runAfter:
      - fetch-source
    params:
      - name: IMAGE
        value: "ghcr.io/vrutkovs/color-demo:$(tasks.fetch-source.results.commit)"
      - name: CONTEXT
        value: "$(workspaces.source.path)"
    workspaces:
      - name: source
        workspace: app-source
      - name: dockerconfig
        workspace: dockerconfig-ws
  - name: deploy
    params:
      - name: SCRIPT
        value: |
          cd $(workspaces.manifest-dir.path)/manifests/overlays/default
          NAMESPACE="$(context.pipelineRun.namespace)"
          echo "Namespace: ${NAMESPACE}"
          echo "Deploying commit $(results.fetch-source.commit)"
          echo "images:" >> kustomization.yaml
          echo "- name: ghcr.io/vrutkovs/color-demo:latest" >> kustomization.yaml
          echo "  newName: ghcr.io/vrutkovs/color-demo" >> kustomization.yaml
          echo "  newTag: $(results.fetch-source.commit)" >> kustomization.yaml
          oc apply -k .
          oc rollout status deploy/colors -w
    runAfter:
      - build-image
    taskRef:
      kind: ClusterTask
      name: openshift-client
    workspaces:
      - name: manifest-dir
        workspace: app-source
  - name: tag-as-latest
    taskRef:
      kind: ClusterTask
      name: skopeo-copy
    runAfter:
      - deploy
    params:
      - name: srcImageURL
        value: 'docker://ghcr.io/vrutkovs/color-demo:$(results.fetch-source.commit)'
      - name: destImageURL
        value: 'docker://ghcr.io/vrutkovs/color-demo:latest'
