apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesJson6902:
- path: deployment-patch.yaml
  target:
    group: apps
    kind: Deployment
    name: colors
    version: v1
resources:
- 01-build-pipeline.yaml
- 02-pipeline-run.yaml
