apiVersion: v1
kind: Secret
metadata:
  name: vault-configuration
stringData:
  AVP_TYPE: vault
  AVP_AUTH_TYPE: k8s
  AVP_K8S_ROLE: vault_plugin
  VAULT_ADDR: https://vault-internal.vault.svc:8200
type: Opaque
