apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin
  namespace: openshift-gitops
data:
  avp.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin
    spec:
      allowConcurrency: true
      generate:
        command:
          - argocd-vault-plugin
          - generate
          - "."
      lockRepo: false
