apiVersion: autoscaling.openshift.io/v1
kind: ClusterAutoscaler
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  balanceSimilarNodeGroups: true
  scaleDown:
    enabled: true
