apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: vrutkovs-demo-gfc65-worker-a
  namespace: openshift-machine-api
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-machine-role: infra
        machine.openshift.io/cluster-api-machine-type: infra
        node-role.kubernetes.io/infra: ""
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/infra: ""
      providerSpec:
        value:
          machineType: n2-highmem-8
      taints:
      - key: node-role.kubernetes.io/infra
        effect: NoSchedule
        value: reserved
---
apiVersion: autoscaling.openshift.io/v1beta1
kind: MachineAutoscaler
metadata:
  name: worker-us-east-2a
  namespace: openshift-machine-api
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet
    name: vrutkovs-demo-gfc65-worker-a
---
apiVersion: autoscaling.openshift.io/v1beta1
kind: MachineAutoscaler
metadata:
  name: worker-us-east-2b
  namespace: openshift-machine-api
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet
    name: vrutkovs-demo-gfc65-worker-b
---
apiVersion: autoscaling.openshift.io/v1beta1
kind: MachineAutoscaler
metadata:
  name: worker-us-east-2c
  namespace: openshift-machine-api
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet
    name: vrutkovs-demo-gfc65-worker-c
