apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: cert-manager-operator
  namespace: cert-manager-operator
spec:
  upgradeStrategy: Default
  targetNamespaces:
    - cert-manager-operator
