---
apiVersion: hypershift.openshift.io/v1beta1
kind: NodePool
metadata:
  name: vrutkovs-dev-us-east-2a
  namespace: clusters
spec:
  platform:
    aws:
      instanceType: m5.xlarge
---
apiVersion: hypershift.openshift.io/v1beta1
kind: NodePool
metadata:
  name: vrutkovs-stage-us-east-2a
  namespace: clusters
spec:
  platform:
    kubevirt:
      compute:
        cores: 8
        memory: 16Gi
      rootVolume:
        persistent:
          size: 50Gi
        type: Persistent
    type: KubeVirt
---
apiVersion: hypershift.openshift.io/v1beta1
kind: NodePool
metadata:
  name: vrutkovs-prod-eu-eu-west-3a
  namespace: clusters
spec:
  clusterName: vrutkovs-prod-eu
  management:
    autoRepair: false
    replace:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
      strategy: RollingUpdate
    upgradeType: Replace
  nodeDrainTimeout: 0s
  replicas: 2
  platform:
    aws:
      instanceType: m5.xlarge
---
apiVersion: hypershift.openshift.io/v1beta1
kind: NodePool
metadata:
  name: vrutkovs-prod-us-us-west-2a
  namespace: clusters
spec:
  clusterName: vrutkovs-prod-us
  management:
    autoRepair: false
    replace:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
      strategy: RollingUpdate
    upgradeType: Replace
  nodeDrainTimeout: 0s
  replicas: 2
  platform:
    aws:
      instanceType: m5.xlarge
