apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: global-load-balancer-operator
  namespace: global-load-balancer-operator
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: global-load-balancer-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
