apiVersion: redhatcop.redhat.io/v1alpha1
kind: GlobalDNSZone
metadata:
  name: external-dns-zone
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  domain: devcluster.openshift.com
  provider:
    route53:
      credentialsSecretRef:
        name: aws-creds
        namespace: clusters
      zoneID: Z3URY6TWQ91KVV
