apiVersion: redhatcop.redhat.io/v1alpha1
kind: GlobalDNSRecord
metadata:
  name: workload-global-record
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  name: kcd-vrutkovs-demo.devcluster.openshift.com
  endpoints:
  - clusterName: prodeu
    clusterCredentialRef:
      name: admin-kubeconfig
      namespace: clusters-vrutkovs-prod-eu
    loadBalancerServiceRef:
      name: router-default
      namespace: openshift-ingress
  - clusterName: produs
    clusterCredentialRef:
      name: admin-kubeconfig
      namespace: clusters-vrutkovs-prod-us
    loadBalancerServiceRef:
      name: router-default
      namespace: openshift-ingress
  ttl: 60
  loadBalancingPolicy: Geoproximity
  globalZoneRef:
    name: external-dns-zone
  healthCheck:
    failureThreshold: 3
    httpGet:
      host: kcd-vrutkovs-demo.devcluster.openshift.com
      path: /
      port: 80
      scheme: HTTP
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
