apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesJson6902:
- path: zero-replicas.yaml
  target:
    group: apps
    kind: Deployment
    name: colors
    version: v1
resources:
- rollout.yaml
- global-lb.yaml
- pdb.yaml
