apiVersion: v1
kind: Secret
metadata:
  name: server-settings
type: Opaque
stringData:
  MODEL_TOKEN: ""
  MODEL_ENDPOINT: "https://muchanizer-predictor-muchanizer.apps.vrutkovs.devcluster.openshift.com/v1/models/model:predict"
  TELEGRAM_TOKEN: "<path:secret/data/muchanizer#telegram-token>"
  HF_TOKEN: "<path:secret/data/muchanizer#hf-token>"
