apiVersion: v1
kind: Secret
metadata:
  name: settings
type: Opaque
stringData:
  .env: |
    TELEGRAM_TOKEN = "<path:secret/data/muchanizer#telegram-token>"
    MODEL_TOKEN = ""
    MODEL_ENDPOINT = "https://muchanizer-predictor-muchanizer.apps.vrutkovs.devcluster.openshift.com/v1/models/model:predict"
    STRENGTH = 0.66
    GUIDANCE_SCALE = 4.0
  HF_TOKEN: "<path:secret/data/muchanizer#hf-token>"
  MODEL_ID: "stabilityai/stable-diffusion-xl-base-1.0"
  CONTROLNET_MODEL: "diffusers/controlnet-canny-sdxl-1.0"
  LORA_MODEL: "KappaNeuro/alphonse-mucha-style"
  LORA_WEIGHT_NAME: "Alphonse Mucha Style.safetensors"
