---
apiVersion: hypershift.openshift.io/v1beta1
kind: NodePool
metadata:
  name: vrutkovs-prod-us-us-west-2a
  namespace: clusters
spec:
  clusterName: vrutkovs-prod-us
  management:
    autoRepair: true
    upgradeType: InPlace
  nodeDrainTimeout: 0s
  replicas: 1
  platform:
    aws:
      instanceType: g4dn.4xlarge
    type: AWS
