apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: store-password-in-vault
  namespace: stackrox
spec:
  template:
    spec:
      containers:
        - image: quay.io/openshift/origin-cli:4.16
          env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: central-htpasswd
                  key: password
          command:
            - /bin/bash
            - -c
            - |
              #!/usr/bin/env bash
              oc -n vault exec -ti vault-0 -- bash <<EOF
                set -eux
                export VAULT_ADDR=https://localhost:8200
                export VAULT_SKIP_VERIFY=true
                export VAULT_CACERT=/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
                vault kv put secret/acs-htpasswd password="${PASSWORD}"
              EOF
          imagePullPolicy: Always
          name: store-password-in-vault
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
