apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  aws_access_key_id: <path:secret/data/aws-creds#aws_access_key_id>
  aws_secret_access_key: <path:secret/data/aws-creds#aws_secret_access_key>
  baseDomain: <path:secret/data/aws-creds#baseDomain>
  pullSecret: <path:secret/data/aws-creds#pullSecret>
  ssh-privatekey: <path:secret/data/aws-creds#ssh-privatekey>
  ssh-publickey: <path:secret/data/aws-creds#ssh-publickey>
  ssh-publickey: <path:secret/data/aws-creds#ssh-publickey>
