apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: vrutkovs-stage
  labels:
    cluster.open-cluster-management.io/clusterset: stage
spec:
  hubAcceptsClient: true
  leaseDurationSeconds: 60
