apiVersion: hypershift.openshift.io/v1beta1
kind: HostedCluster
metadata:
  annotations:
    cluster.open-cluster-management.io/hypershiftdeployment: clusters/vrutkovs-prod-us
    cluster.open-cluster-management.io/managedcluster-name: vrutkovs-prod-us
  resourceVersion: '236526'
  name: vrutkovs-prod-us
  namespace: clusters
  finalizers:
    - hypershift.openshift.io/finalizer
    - hypershift.io/aws-oidc-discovery
  labels:
    hypershift.openshift.io/auto-created-for-infra: vrutkovs-prod-us
spec:
  fips: false
  release:
    image: 'quay.io/openshift-release-dev/ocp-release:4.12.16-x86_64'
  dns:
    baseDomain: devcluster.openshift.com
    privateZoneID: Z01416432S3CML1BL66NB
    publicZoneID: Z3URY6TWQ91KVV
  controllerAvailabilityPolicy: SingleReplica
  infraID: vrutkovs-prod-us
  etcd:
    managed:
      storage:
        persistentVolume:
          size: 4Gi
          storageClassName: gp3-csi
        type: PersistentVolume
    managementType: Managed
  infrastructureAvailabilityPolicy: SingleReplica
  platform:
    aws:
      cloudProviderConfig:
        subnet:
          id: subnet-06fff75006abe2da4
        vpc: vpc-024821ec392633573
        zone: us-west-2a
      endpointAccess: Public
      region: us-west-2
      resourceTags:
        - key: kubernetes.io/cluster/vrutkovs-prod-us
          value: owned
      rolesRef:
        controlPlaneOperatorARN: 'arn:aws:iam::269733383066:role/vrutkovs-prod-us-control-plane-operator'
        imageRegistryARN: >-
          arn:aws:iam::269733383066:role/vrutkovs-prod-us-openshift-image-registry
        ingressARN: 'arn:aws:iam::269733383066:role/vrutkovs-prod-us-openshift-ingress'
        kubeCloudControllerARN: 'arn:aws:iam::269733383066:role/vrutkovs-prod-us-cloud-controller'
        networkARN: >-
          arn:aws:iam::269733383066:role/vrutkovs-prod-us-cloud-network-config-controller
        nodePoolManagementARN: 'arn:aws:iam::269733383066:role/vrutkovs-prod-us-node-pool'
        storageARN: >-
          arn:aws:iam::269733383066:role/vrutkovs-prod-us-aws-ebs-csi-driver-controller
    type: AWS
  secretEncryption:
    aescbc:
      activeKey:
        name: vrutkovs-prod-us-etcd-encryption-key
    type: aescbc
  networking:
    clusterNetwork:
      - cidr: 10.132.0.0/14
    machineNetwork:
      - cidr: 10.0.0.0/16
    networkType: OVNKubernetes
    serviceNetwork:
      - cidr: 172.31.0.0/16
  clusterID: 4ac2ce53-90b9-47bf-a549-693b5ea06f85
  pullSecret:
    name: vrutkovs-prod-us-pull-secret
  issuerURL: 'https://vrutkovs-hypershift-demo.s3.us-east-2.amazonaws.com/vrutkovs-prod-us'
  sshKey:
    name: vrutkovs-prod-us-ssh-key
  autoscaling: {}
  olmCatalogPlacement: management
  services:
    - service: APIServer
      servicePublishingStrategy:
        type: LoadBalancer
    - service: OAuthServer
      servicePublishingStrategy:
        type: Route
    - service: Konnectivity
      servicePublishingStrategy:
        type: Route
    - service: Ignition
      servicePublishingStrategy:
        type: Route
    - service: OVNSbDb
      servicePublishingStrategy:
        type: Route
