apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: vrutkovs-prod-us
  labels:
    cluster.open-cluster-management.io/clusterset: prod
spec:
  hubAcceptsClient: true
  leaseDurationSeconds: 60
---
apiVersion: internal.open-cluster-management.io/v1beta1
kind: ManagedClusterInfo
metadata:
  name: vrutkovs-prod-us
  namespace: vrutkovs-prod-us
spec: {}
