apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  addon:
    params:
      - name: clusterTasks
        value: 'true'
      - name: communityClusterTasks
        value: 'false'
      - name: pipelineTemplates
        value: 'false'
  pipeline:
    params:
      - name: enableMetrics
        value: 'true'
  profile: all
  pruner:
    resources:
      - taskrun
      - pipelinerun
    keep: 3
    schedule: '@daily'
  targetNamespace: openshift-pipelines
