apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spoke-settings
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/instance: argocd
spec:
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    directory:
      recurse: true
    path: apps/spoke-settings
    repoURL: 'https://github.com/vrutkovs/kcd-cz-demo'
    targetRevision: HEAD
  syncPolicy:
    automated: {}
