apiVersion: v1
kind: Secret
metadata:
  name: aws-sts-creds
  namespace: clusters
  annotations:
    argocd.argoproj.io/sync-wave: "2"
type: Opaque
stringData:
  sts-creds.json: <path:secret/data/sts-creds#sts-creds>
  role-arn: <path:secret/data/sts-creds#role-arn>
