apiVersion: v1
kind: Secret
metadata:
  name: aws-creds
  namespace: clusters
  annotations:
    avp.kubernetes.io/path: "secret/data/aws-creds"
    argocd.argoproj.io/sync-wave: "2"
type: Opaque
stringData:
  aws_access_key_id: <aws_access_key_id>
  aws_secret_access_key: <aws_secret_access_key>
  baseDomain: <baseDomain>
  pullSecret: <pullSecret>
  ssh-privatekey: <ssh-privatekey>
  ssh-publickey: <ssh-publickey>
  ssh-publickey: <ssh-publickey>
