apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  namespace: open-cluster-management
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  nodeSelector:
    node-role.kubernetes.io/infra: ""
  tolerations:
  - key: node-role.kubernetes.io/infra
    effect: NoSchedule
    operator: Exists
  availabilityConfig: Basic
  overrides:
    components:
    - enabled: true
      name: hypershift-preview
    - enabled: true
      name: hypershift-local-hosting
    - enabled: true
      name: console
    - enabled: true
      name: insights
    - enabled: true
      name: grc
    - enabled: true
      name: cluster-lifecycle
    - enabled: true
      name: multicluster-engine
    - enabled: true
      name: app-lifecycle
    - enabled: false
      name: volsync
    - enabled: false
      name: search
    - enabled: false
      name: cluster-backup
