apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  name: hypershift-addon
  namespace: local-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  installNamespace: open-cluster-management-agent-addon
