apiVersion: v1
kind: Secret
metadata:
  name: hypershift-operator-oidc-provider-s3-credentials
  namespace: local-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
type: Opaque
stringData:
  bucket: <path:secret/data/oidc#bucket>
  region: <path:secret/data/oidc#region>
  credentials: <path:secret/data/oidc#credentials>
