apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oidc
  namespace: local-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  target:
    name: hypershift-operator-oidc-provider-s3-credentials
  dataFrom:
  - extract:
      key: /local-cluster/oidc
