apiVersion: v1
kind: ServiceAccount
metadata:
  name: hcp-admin
  namespace: clusters
  annotations:
    argocd.argoproj.io/sync-wave: "7"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hcp-admin-hypershift-operator
  annotations:
    argocd.argoproj.io/sync-wave: "8"
subjects:
  - kind: ServiceAccount
    name: hcp-admin
    namespace: clusters
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hypershift-operator
