apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: thanos-object-storage
  dataFrom:
  - extract:
      key: "secret/thanos-settings"
