apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
  annotations:
    argocd.argoproj.io/sync-wave: "2"
type: Opaque
stringData:
  thanos.yaml: <path:secret/data/thanos-settings#thanos.yaml>
