apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acs-securecluster
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/instance: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: apps/acs/securecluster
    repoURL: 'https://github.com/vrutkovs/kcd-cz-demo'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: -1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1h
