---
apiVersion: v1
kind: Secret
metadata:
  name: vrutkovs-stage-pull-secret
  namespace: clusters
  annotations:
    argocd.argoproj.io/sync-wave: "1"
stringData:
  .dockerconfigjson: <path:secret/data/aws-creds#pullSecret>
---
apiVersion: v1
kind: Secret
metadata:
  name: vrutkovs-stage-etcd-encryption-key
  namespace: clusters
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  key: YOIpvBeis2FlRCEtKGUMrY4jjnP8JeWaKG6jgRFcTqY=
---
apiVersion: v1
kind: Secret
metadata:
  name: vrutkovs-stage-ssh-key
  namespace: clusters
  annotations:
    argocd.argoproj.io/sync-wave: "1"
stringData:
  id_rsa.pub: <path:secret/data/aws-creds#ssh-publickey>
