kind: ConfigMap
apiVersion: v1
metadata:
  name: cluster-name
  namespace: stackrox
data:
  name: prod-eu
---
apiVersion: v1
kind: Secret
metadata:
  name: central-htpasswd
  namespace: stackrox
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
type: Opaque
stringData:
  password: <path:secret/data/acs-htpasswd#password>
