apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: knative-serving
  namespace: knative-serving
spec:
  config:
    features:
      secure-pod-defaults: enabled
