apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  outputs:
    - name: loki-applications
      type: "loki"
      url: https://logging-loki-openshift-logging.apps.vrutkovs-demo.origin-gce.dev.openshift.com/api/logs/v1/application
      secret:
        name: external-log-forwarder-token
    - name: loki-infra
      type: "loki"
      url: https://logging-loki-openshift-logging.apps.vrutkovs-demo.origin-gce.dev.openshift.com/api/logs/v1/infrastructure
      secret:
        name: external-log-forwarder-token
  pipelines:
    - name: application-logs
      labels:
        clusterId: prod-eu
      inputRefs:
        - application
      outputRefs:
        - loki-applications
    - name: infra-logs
      labels:
        clusterId: prod-eu
      inputRefs:
        - infrastructure
      outputRefs:
        - loki-infra
