apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: create-cluster-init
  namespace: stackrox
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - create
      - patch
      - update
  - apiGroups:
      - platform.stackrox.io
    resources:
      - securedclusters
    verbs:
      - get
      - list
      - patch
      - update
