apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-prometheus
  namespace: openshift-ingress-operator
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretTargetRef:
    - parameter: bearerToken
      name: metrics-reader-token-87kv2
      key: token
    - parameter: ca
      name: metrics-reader-token-87kv2
      key: ca.crt
