apiVersion: hypershift.openshift.io/v1beta1
kind: NodePool
metadata:
  name: vrutkovs-dev
  namespace: clusters
  annotations:
    cluster.open-cluster-management.io/hypershiftdeployment: local-cluster/vrutkovs-dev
    cluster.open-cluster-management.io/managedcluster-name: vrutkovs-dev
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  clusterName: vrutkovs-dev
  management:
    autoRepair: true
    upgradeType: InPlace
  nodeDrainTimeout: 0s
  release:
    image: quay.io/okd/scos-release:4.15.0-0.okd-scos-2024-01-18-223523
  replicas: 1
  platform:
    kubevirt:
      compute:
        cores: 4
        memory: 16Gi
      rootVolume:
        persistent:
          size: 50Gi
        type: Persistent
      nodeSelector:
        node-role.kubernetes.io/virtualization: ""
    type: KubeVirt
