---
apiVersion: v1
kind: Secret
metadata:
  name: vrutkovs-dev-pull-secret
  namespace: clusters
  annotations:
    argocd.argoproj.io/sync-wave: "1"
stringData:
  .dockerconfigjson: <path:secret/data/aws-creds#pullSecret>
---
apiVersion: v1
kind: Secret
metadata:
  name: vrutkovs-dev-etcd-encryption-key
  namespace: clusters
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  key: YOIpvBeis2FlRCEtKGUMrY4jjnP8JeWaKG6jgRFcTqY=
---
apiVersion: v1
kind: Secret
metadata:
  name: vrutkovs-dev-ssh-key
  namespace: clusters
  annotations:
    argocd.argoproj.io/sync-wave: "1"
stringData:
  id_rsa.pub: <path:secret/data/aws-creds#ssh-publickey>
---
apiVersion: v1
kind: Secret
metadata:
  name: github-oauth-secret-dev
  namespace: clusters
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  clientSecret: <path:secret/data/oauth-dev#secret>
