apiVersion: hypershift.openshift.io/v1beta1
kind: HostedCluster
metadata:
  annotations:
    cluster.open-cluster-management.io/hypershiftdeployment: clusters/vrutkovs-prod-eu
    cluster.open-cluster-management.io/managedcluster-name: vrutkovs-prod-eu
    argocd.argoproj.io/sync-wave: "1"
  name: vrutkovs-prod-eu
  namespace: clusters
  finalizers:
    - hypershift.openshift.io/finalizer
    - hypershift.io/aws-oidc-discovery
  labels:
    hypershift.openshift.io/auto-created-for-infra: vrutkovs-prod-eu
spec:
  fips: false
  release:
    image: 'quay.io/openshift-release-dev/ocp-release:4.14.3-x86_64'
  dns:
    baseDomain: devcluster.openshift.com
  controllerAvailabilityPolicy: SingleReplica
  infraID: vrutkovs-prod-eu
  etcd:
    managed:
      storage:
        persistentVolume:
          size: 8Gi
        type: PersistentVolume
    managementType: Managed
  infrastructureAvailabilityPolicy: SingleReplica
  platform:
    aws:
      cloudProviderConfig:
        zone: eu-west-3a
      endpointAccess: Public
      region: eu-west-3
      resourceTags:
        - key: kubernetes.io/cluster/vrutkovs-prod-eu
          value: owned
    type: AWS
  secretEncryption:
    aescbc:
      activeKey:
        name: vrutkovs-prod-eu-etcd-encryption-key
    type: aescbc
  networking:
    clusterNetwork:
      - cidr: 10.132.0.0/14
    machineNetwork:
      - cidr: 10.0.0.0/16
    networkType: OVNKubernetes
    serviceNetwork:
      - cidr: 172.31.0.0/16
  clusterID: 4918b4b7-bc83-4cb6-bd9a-15c61fdfd848
  pullSecret:
    name: vrutkovs-prod-eu-pull-secret
  issuerURL: 'https://vrutkovs-hypershift-demo.s3.us-east-1.amazonaws.com/vrutkovs-prod-eu'
  sshKey:
    name: vrutkovs-prod-eu-ssh-key
  autoscaling: {}
  olmCatalogPlacement: management
  services:
    - service: APIServer
      servicePublishingStrategy:
        type: LoadBalancer
    - service: OAuthServer
      servicePublishingStrategy:
        type: Route
    - service: Konnectivity
      servicePublishingStrategy:
        type: Route
    - service: Ignition
      servicePublishingStrategy:
        type: Route
    - service: OVNSbDb
      servicePublishingStrategy:
        type: Route
