apiVersion: hypershift.openshift.io/v1beta1
kind: NodePool
metadata:
  name: vrutkovs-prod-eu-eu-west-3a
  namespace: clusters
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  clusterName: vrutkovs-prod-eu
  management:
    autoRepair: true
    upgradeType: Replace
  nodeDrainTimeout: 0s
  replicas: 1
  platform:
    aws:
      instanceType: g4dn.4xlarge
    type: AWS
