---
apiVersion: v1
kind: Secret
metadata:
  name: github-oauth-secret-prod-eu
  namespace: clusters
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  clientSecret: <path:secret/data/oauth-prod-eu#secret>
