apiVersion: hypershift.openshift.io/v1beta1
kind: HostedCluster
metadata:
  annotations:
    cluster.open-cluster-management.io/hypershiftdeployment: clusters/vrutkovs-prod-eu
    cluster.open-cluster-management.io/managedcluster-name: vrutkovs-prod-eu
  resourceVersion: '249318'
  name: vrutkovs-prod-eu
  namespace: clusters
  finalizers:
    - hypershift.openshift.io/finalizer
    - hypershift.io/aws-oidc-discovery
  labels:
    hypershift.openshift.io/auto-created-for-infra: vrutkovs-prod-eu
spec:
  fips: false
  release:
    image: 'quay.io/openshift-release-dev/ocp-release:4.12.16-x86_64'
  dns:
    baseDomain: devcluster.openshift.com
    privateZoneID: Z10279342DWIDYJHJBIDZ
    publicZoneID: Z3URY6TWQ91KVV
  controllerAvailabilityPolicy: SingleReplica
  infraID: vrutkovs-prod-eu
  etcd:
    managed:
      storage:
        persistentVolume:
          size: 4Gi
          storageClassName: gp3-csi
        type: PersistentVolume
    managementType: Managed
  infrastructureAvailabilityPolicy: SingleReplica
  platform:
    aws:
      cloudProviderConfig:
        subnet:
          id: subnet-08cfca02c4b1244c2
        vpc: vpc-00f03d7da8e2afd56
        zone: eu-west-3a
      endpointAccess: Public
      region: eu-west-3
      resourceTags:
        - key: kubernetes.io/cluster/vrutkovs-prod-eu
          value: owned
      rolesRef:
        controlPlaneOperatorARN: 'arn:aws:iam::269733383066:role/vrutkovs-prod-eu-control-plane-operator'
        imageRegistryARN: >-
          arn:aws:iam::269733383066:role/vrutkovs-prod-eu-openshift-image-registry
        ingressARN: 'arn:aws:iam::269733383066:role/vrutkovs-prod-eu-openshift-ingress'
        kubeCloudControllerARN: 'arn:aws:iam::269733383066:role/vrutkovs-prod-eu-cloud-controller'
        networkARN: >-
          arn:aws:iam::269733383066:role/vrutkovs-prod-eu-cloud-network-config-controller
        nodePoolManagementARN: 'arn:aws:iam::269733383066:role/vrutkovs-prod-eu-node-pool'
        storageARN: >-
          arn:aws:iam::269733383066:role/vrutkovs-prod-eu-aws-ebs-csi-driver-controller
    type: AWS
  secretEncryption:
    aescbc:
      activeKey:
        name: vrutkovs-prod-eu-etcd-encryption-key
    type: aescbc
  networking:
    clusterNetwork:
      - cidr: 10.132.0.0/14
    machineNetwork:
      - cidr: 10.0.0.0/16
    networkType: OVNKubernetes
    serviceNetwork:
      - cidr: 172.31.0.0/16
  clusterID: e067fbf7-5aa3-4b2d-a2a2-82599f6fba4b
  pullSecret:
    name: vrutkovs-prod-eu-pull-secret
  issuerURL: 'https://vrutkovs-hypershift-demo.s3.us-east-2.amazonaws.com/vrutkovs-prod-eu'
  sshKey:
    name: vrutkovs-prod-eu-ssh-key
  autoscaling: {}
  olmCatalogPlacement: management
  services:
    - service: APIServer
      servicePublishingStrategy:
        type: LoadBalancer
    - service: OAuthServer
      servicePublishingStrategy:
        type: Route
    - service: Konnectivity
      servicePublishingStrategy:
        type: Route
    - service: Ignition
      servicePublishingStrategy:
        type: Route
    - service: OVNSbDb
      servicePublishingStrategy:
        type: Route
