apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: vrutkovs-prod-eu
  labels:
    cluster.open-cluster-management.io/clusterset: prod
spec:
  hubAcceptsClient: true
  leaseDurationSeconds: 60
