apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: logging-loki-s3
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: logging-loki-gcp
  dataFrom:
  - extract:
      key: "secret/logging-loki-gcp"
