apiVersion: v1
kind: Secret
metadata:
  name: logging-loki-gcp
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "4"
type: Opaque
stringData:
  bucketname: <path:secret/data/logging-loki-gcp#bucketname>
  key.json: <path:secret/data/logging-loki-gcp#key.json>
