apiVersion: v1
kind: Secret
metadata:
  name: logging-loki-gcp
  namespace: openshift-logging
  annotations:
    avp.kubernetes.io/path: "secret/data/logging-loki-gcp"
    argocd.argoproj.io/sync-wave: "4"
type: Opaque
stringData:
  bucketname: <bucketname>
  key.json: <key.json>
