apiVersion: operator.openshift.io/v1
kind: Console
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  plugins:
    - monitoring-plugin
    - mce
    - acm
    - logging-view-plugin
    - kubevirt-plugin
    - gitops-plugin
    - flightctl-plugin
    - networking-console-plugin
