apiVersion: observability.openshift.io/v1alpha1
kind: UIPlugin
metadata:
  annotations:
    observability.openshift.io/api-support: GeneralAvailability
  name: logging
spec:
  logging:
    logsLimit: 100
    lokiStack:
      name: logging-loki
      namespace: openshift-logging
  type: Logging
