apiVersion: v1
kind: Secret
metadata:
  name: github-oauth-secret
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  clientSecret: <path:secret/data/oauth-prod-us#secret>
