apiVersion: v1
kind: Secret
metadata:
  name: external-log-forwarder-token
  namespace: openshift-logging
  annotations:
    avp.kubernetes.io/path: "secret/data/external-log-forwarder"
    argocd.argoproj.io/sync-wave: "5"
type: Opaque
stringData:
  token: <token>
