apiVersion: v1
kind: Secret
metadata:
  name: external-log-forwarder-token
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "5"
type: Opaque
stringData:
  token: <path:secret/data/external-log-forwarder#token>
