apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: grafana-operator
  namespace: grafana-operator
spec:
  upgradeStrategy: Default
  targetNamespaces:
    - grafana-operator
