---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-proxy
  namespace: grafana-operator
  annotations:
    argocd.argoproj.io/sync-wave: "3"
type: Opaque
data:
  session_secret: Y2hhbmdlIG1lCg==
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    config.openshift.io/inject-trusted-cabundle: "true"
  name: ocp-injected-certs
  namespace: grafana-operator
