apiVersion: v1
kind: Secret
metadata:
  name: grafana-k8s-proxy
  namespace: grafana-operator
  annotations:
    argocd.argoproj.io/sync-wave: "3"
type: Opaque
data:
  session_secret: Y2hhbmdlIG1lCg==
