apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: thanos
  namespace: grafana-operator
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasource:
    access: proxy
    editable: false
    isDefault: false
    jsonData:
      httpHeaderName1: 'Authorization'
      timeInterval: 5s
      tlsSkipVerify: true
    secureJsonData:
      httpHeaderValue1: 'Bearer sha256~5CJAGBFB3iKpUwV0MyMEZZ8qmRUE1C_AuO-2ggXHv_o'
    name: Observatorium
    type: prometheus
    url: 'http://rbac-query-proxy.open-cluster-management-observability.svc.cluster.local:8080'
