apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-stage-certmanager
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: stage-cluster
        requeueAfterSeconds: 180
  template:
    metadata:
      name: 'cluster-{{name}}-certmanager'
    spec:
      destination:
        namespace: workload
        server: '{{server}}'
      project: default
      source:
        path: 'apps/cert-manager'
        repoURL: https://github.com/vrutkovs/kcd-cz-demo
        targetRevision: HEAD
        directory:
          recurse: true
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
          - Validate=false
          - Replace=false
          - PrunePropagationPolicy=background
