apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-prod
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: prod-cluster
        requeueAfterSeconds: 180
  template:
    metadata:
      name: 'demo-prod-{{name}}'
    spec:
      destination:
        namespace: ai-prompt
        server: '{{server}}'
      project: default
      source:
        path: 'manifests/'
        repoURL: https://github.com/vrutkovs/openshift-ai-prompt
        targetRevision: 86422eb
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        retry:
          limit: -1
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 1h
      ignoreDifferences:
      - group: apps
        kind: Deployment
        jsonPointers:
        - /spec/template/spec/containers/0/image
        - /spec/template/spec/containers/1/image
