apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-prod-rollouts
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: prod-cluster
        requeueAfterSeconds: 180
  template:
    metadata:
      name: 'cluster-{{name}}-rollouts'
    spec:
      destination:
        namespace: argo-rollouts
        server: '{{server}}'
      project: default
      source:
        path: apps/rollouts
        repoURL: 'https://github.com/vrutkovs/kcd-cz-demo'
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
          - Validate=false
          - Replace=false
          - PrunePropagationPolicy=background
