apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: podhunt-prod
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: prod-cluster
        requeueAfterSeconds: 180
  template:
    metadata:
      name: 'podhunt-prod-{{name}}'
    spec:
      destination:
        namespace: workload
        server: '{{server}}'
      project: default
      source:
        path: 'manifests/overlays/{{name}}/'
        repoURL: 'https://github.com/vrutkovs/k8s-podhunt'
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: -1
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 1h
