apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workload-stage
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: stage-cluster
        requeueAfterSeconds: 180
  template:
    metadata:
      name: 'workload-stage'
    spec:
      destination:
        namespace: 'workload'
        server: '{{server}}'
      project: default
      source:
        path: manifests/pipeline
        repoURL: https://github.com/vrutkovs/color-demo
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
          - Validate=false
          - Replace=false
          - PrunePropagationPolicy=background
