apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workload-dev
  namespace: openshift-gitops
spec:
  generators:
    - matrix:
        generators:
        - pullRequest:
            github:
              owner: vrutkovs
              repo: color-demo
              labels:
              - preview
              tokenRef:
                secretName: github-token
                key: token
            requeueAfterSeconds: 5
        - clusterDecisionResource:
            configMapRef: acm-placement
            labelSelector:
              matchLabels:
                cluster.open-cluster-management.io/placement: dev-cluster
            requeueAfterSeconds: 180
  template:
    metadata:
      name: 'workload-dev-{{branch}}-{{number}}'
    spec:
      destination:
        namespace: 'workload-{{branch}}-{{number}}'
        server: '{{server}}'
      project: default
      source:
        path: pipelines/dev
        repoURL: https://github.com/vrutkovs/kcd-cz-demo
        targetRevision: HEAD
        helm:
          parameters:
           - name: repo_url
             value: 'https://github.com/vrutkovs/color-demo'
           - name: repo_sha
             value: '{{head_sha}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
          - Validate=false
          - Replace=false
          - PrunePropagationPolicy=background
