apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workload-prod
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: prod-cluster
        requeueAfterSeconds: 180
  template:
    metadata:
      name: 'workload-prod-{{name}}'
    spec:
      destination:
        namespace: workload
        server: '{{server}}'
      project: default
      source:
        path: 'manifests/overlays/{{name}}/'
        repoURL: https://github.com/vrutkovs/color-demo
        targetRevision: 6d7f0da66f5a8be964d6107bf1c58546c0c0f71e
        kustomize:
          images:
          - ghcr.io/vrutkovs/color-demo:6d7f0da66f5a8be964d6107bf1c58546c0c0f71e
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
          - Validate=false
          - Replace=false
          - PrunePropagationPolicy=background
