apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-prod-eu
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/instance: argocd
spec:
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: apps/clusters/prod-eu
    repoURL: 'https://github.com/vrutkovs/kcd-cz-demo'
    targetRevision: HEAD
