apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kargo
  project: default
  source:
    chart: kargo
    repoURL: ghcr.io/akuity/kargo-charts/kargo
    targetRevision: 0.3.0
    helm:
      releaseName: kargo
      values: |
        api:
          nodeSelector:
            node-role.kubernetes.io/infra: ""
          tolerations:
          - key: node-role.kubernetes.io/infra
            effect: NoSchedule
            operator: Exists
          ingress:
            enabled: true
          adminAccount:
            password: admin
        controller:
          argocd:
            namespace: openshift-gitops
