apiVersion: v1
kind: Secret
metadata:
  name: github-token
  namespace: openshift-gitops
  annotations:
    avp.kubernetes.io/path: "secret/data/github-token"
type: Opaque
stringData:
  token: <token>
