---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-token
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: github-token
  data:
  - secretKey: token
    remoteRef:
      key: "secret/github-token"
---
apiVersion: v1
kind: Secret
metadata:
  name: github-token
  namespace: openshift-gitops
  annotations:
    avp.kubernetes.io/path: "secret/data/github-token"
type: Opaque
stringData:
  token: <token>
