apiVersion: v1
kind: Secret
metadata:
  name: google-secret
  namespace: cert-manager
  annotations:
    avp.kubernetes.io/path: "secret/data/google-creds"
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  service-account.json: <service-account.json>
