apiVersion: v1
kind: Secret
metadata:
  name: google-secret
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  service-account.json: <path:secret/data/google-creds#service-account.json>
