apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: google-secret
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: google-secret
  dataFrom:
  - extract:
      key: "secret/google-creds"
