apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  identityProviders:
  - name: github
    mappingMethod: claim
    type: GitHub
    github:
      clientID: c42f5da56269e2226ea9
      clientSecret:
        name: github-oauth-secret
      teams:
      - okd-project/admins
