apiVersion: platform.stackrox.io/v1alpha1
kind: SecuredCluster
metadata:
  name: hub
  namespace: stackrox
  annotations:
    argocd.argoproj.io/sync-wave: "7"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  monitoring:
    openshift:
      enabled: true
  auditLogs:
    collection: Auto
  admissionControl:
    listenOnUpdates: true
    bypass: BreakGlassAnnotation
    contactImageScanners: DoNotScanInline
    listenOnCreates: true
    replicas: 3
    timeoutSeconds: 20
    listenOnEvents: true
  scanner:
    analyzer:
      scaling:
        autoScaling: Enabled
        maxReplicas: 5
        minReplicas: 2
        replicas: 3
    scannerComponent: AutoSense
  perNode:
    collector:
      collection: EBPF
      imageFlavor: Regular
    taintToleration: TolerateTaints
  clusterName: hub
  centralEndpoint: 'central.stackrox:443'
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: cluster-name
  namespace: stackrox
  annotations:
    argocd.argoproj.io/sync-wave: "7"
data:
  name: hub
