---
apiVersion: v1
kind: Secret
metadata:
  name: vault-configuration
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
stringData:
  AVP_TYPE: vault
  AVP_AUTH_TYPE: k8s
  AVP_K8S_ROLE: vault_plugin
  VAULT_ADDR: https://vault.vault.svc:8200
  VAULT_CACERT: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
type: Opaque
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: vault-plugin
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
data:
  avp.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin
    spec:
      allowConcurrency: true
      discover:
        find:
          command:
            - sh
            - "-c"
            - "find . -name '*.yaml' | xargs -I {} grep \"<path\\|avp\\.kubernetes\\.io\" {} | grep ."
      generate:
        command:
          - argocd-vault-plugin
          - generate
          - "."
      lockRepo: false
